version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: produits vendus par greenweez
        columns:
          - name: products_id
            description: liste des produits
            tests: 
            - unique
            - not_null
          - name: purchSE_PRICE
            description: prix des produits

      - name: sales
        identifier: raw_gz_sales
        description: ventes
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
           warn_after: 
            count: 90
            period: day
        columns:
          - name: date_date
            description: date de la commande
          - name: orders_id
            description: id de la commande
          - name: pdt_id
            description: id du produit
          - name: recette
            description: marge
          - name: quantity
            description: quantité de produit vendu

      - name: ship
        identifier: raw_gz_ship
        description: expedition des commandes
        columns:
          - name: orders_id
            description: id de la commande
            tests: 
              - unique
              - not_null
          - name: shipping_fee
            description: frais d'envoi
          - name: shipping_fee_1
            description: frais d'envoi (pas de diff avec shipping fee)
          - name: logCost
            description: frais logistiques
          - name: ship_cost
            description: coût d'envoi

      - name: adwords
        identifier: raw_gz_adwords 
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPNG_name
          - name: ads_cost
          - name: impression
          - name: click
          

      - name: bing
        identifier: raw_gz_bing
        columns: 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPNG_name
         - name: ads_cost
         - name: impression
         - name: click
      
  
      - name: criteo
        identifier: raw_gz_criteo
        columns: 
        - name: date_date
        - name: paid_source
        - name: campaign_key
        - name: camPNG_name
        - name: ads_cost
        - name: impression
        - name: click

      - name: facebook
        identifier: raw_gz_facebook
        columns: 
        - name: date_date
        - name: paid_source
        - name: campaign_key
        - name: camPNG_name
        - name: ads_cost
        - name: impression
        - name: click

models:
  - name: stg_gz_raw_data__adwords
  - name: stg_gz_raw_data__bing
  - name: stg_gz_raw_data__criteo
  - name: stg_gz_raw_data__facebook