version: 2

sources: 
  - name: gz_raw_data
    tables: 
      - name: raw_gz_product
        identifier: product
        description: produits vendus par greenweez
        columns:
          - name: products_id
          - name: purchSE_PRICE

      - name: raw_gz_sales
        identifier: sales
        description: ventes
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity

      - name: raw_gz_ship
        identifier: ship
        description: expedition des commandes
        columns:
          - name: orders_id
          - name: hipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
